services:
  ros2:
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      DISPLAY: :0
      LIBGL_ALWAYS_SOFTWARE: "1"
      GALLIUM_DRIVER: llvmpipe
      MESA_LOADER_DRIVER_OVERRIDE: llvmpipe
