services:
  ros2:
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /mnt/wslg:/mnt/wslg:rw
    environment:
      DISPLAY: :0
      WAYLAND_DISPLAY: wayland-0
      XDG_RUNTIME_DIR: /mnt/wslg/runtime-dir
      LIBGL_ALWAYS_SOFTWARE: "1"
      GALLIUM_DRIVER: llvmpipe
      MESA_LOADER_DRIVER_OVERRIDE: llvmpipe
