name: Docker Image CI

on:
  push:
    paths:
      - 'Dockerfile'
      - '.devcontainer/**'
      - 'docker/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - '.devcontainer/**'
      - 'docker/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag warrior-dev:${{ github.sha }}
